var myFullName;
console.log(myFullName);
myFullName = "Nitin Navale";
console.log(myFullName);
var myFullName = "Nitin Vilas Navale";
console.log(myFullName);
var myLove = "I Love Only JS";
console.log( myLove);
var firstName;
var lastName;
var age;
var adderess;
var pin_cod;
var gender;
var is_married;
firstName = "Nitin";
lastName = "Navale";
age = "28";
adderess = "sangola";
pin_cod = "413307";
gender =  "male";
is_married = "married";
is_married = "married";
console.log(firstName,lastName,age,adderess,pin_cod,gender,);

